- name: ＴＯＫＹＯ　ＭＸ１
  type: GR
  channel: '16'
- name: ｔｖｋ
  type: GR
  channel: '18'
  isDisabled: false
- name: フジテレビ
  type: GR
  channel: '21'
- name: ＴＢＳ１
  type: GR
  channel: '22'
- name: テレビ東京１
  type: GR
  channel: '23'
- name: テレビ朝日
  type: GR
  channel: '24'
- name: 日テレ１
  type: GR
  channel: '25'
- name: ＮＨＫＥテレ１東京
  type: GR
  channel: '26'
- name: ＮＨＫ総合１・東京
  type: GR
  channel: '27'
- name: イッツコムｃｈ１１
  type: GR
  channel: '30'
  isDisabled: false
- name: イッツコムｃｈ１０
  type: GR
  channel: '60'
  isDisabled: false
- name: ＢＳ朝日１
  type: BS
  channel: BS1_0
  serviceId: 151
  isDisabled: true
- name: ＢＳ朝日２
  type: BS
  channel: BS1_0
  serviceId: 152
  isDisabled: true
- name: ＢＳ朝日３
  type: BS
  channel: BS1_0
  serviceId: 153
  isDisabled: true
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS1_1
  serviceId: 161
  isDisabled: true
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS1_1
  serviceId: 162
  isDisabled: true
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS1_1
  serviceId: 163
  isDisabled: true
- name: ＢＳテレ東
  type: BS
  channel: BS1_2
  serviceId: 171
  isDisabled: true
- name: ＢＳテレ東２
  type: BS
  channel: BS1_2
  serviceId: 172
  isDisabled: true
- name: ＢＳテレ東３
  type: BS
  channel: BS1_2
  serviceId: 173
  isDisabled: true
- name: ＷＯＷＯＷプライム
  type: BS
  channel: BS3_0
  serviceId: 191
  isDisabled: true
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS3_1
  serviceId: 103
  isDisabled: true
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS3_1
  serviceId: 104
  isDisabled: true
- name: ＷＯＷＯＷライブ
  type: BS
  channel: BS5_0
  serviceId: 192
  isDisabled: true
- name: ＷＯＷＯＷシネマ
  type: BS
  channel: BS5_1
  serviceId: 193
  isDisabled: true
- name: ＢＳ１１イレブン
  type: BS
  channel: BS9_0
  serviceId: 211
  isDisabled: true
- name: スターチャンネル１
  type: BS
  channel: BS9_1
  serviceId: 200
  isDisabled: true
- name: ＢＳ１２トゥエルビ
  type: BS
  channel: BS9_2
  serviceId: 222
  isDisabled: true
- name: ＢＳスカパー！
  type: BS
  channel: BS11_0
  serviceId: 241
  isDisabled: true
- name: 放送大学ｅｘ
  type: BS
  channel: BS11_2
  serviceId: 231
  isDisabled: true
- name: 放送大学ｏｎ
  type: BS
  channel: BS11_2
  serviceId: 232
  isDisabled: true
- name: 放送大学ラジオ
  type: BS
  channel: BS11_2
  serviceId: 531
  isDisabled: true
- name: ＢＳ釣りビジョン
  type: BS
  channel: BS11_2
  serviceId: 251
  isDisabled: true
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
  isDisabled: true
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 142
  isDisabled: true
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 143
  isDisabled: true
- name: ＢＳフジ・１８１
  type: BS
  channel: BS13_1
  serviceId: 181
  isDisabled: true
- name: ＢＳフジ・１８２
  type: BS
  channel: BS13_1
  serviceId: 182
  isDisabled: true
- name: ＢＳフジ・１８３
  type: BS
  channel: BS13_1
  serviceId: 183
  isDisabled: true
- name: ＢＳアニマックス
  type: BS
  channel: BS13_2
  serviceId: 236
  isDisabled: true
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 101
  isDisabled: true
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 102
  isDisabled: true
- name: スターチャンネル２
  type: BS
  channel: BS15_1
  serviceId: 201
  isDisabled: true
- name: スターチャンネル３
  type: BS
  channel: BS15_1
  serviceId: 202
  isDisabled: true
- name: Ｊ　ＳＰＯＲＴＳ　４
  type: BS
  channel: BS19_0
  serviceId: 245
  isDisabled: true
- name: Ｊ　ＳＰＯＲＴＳ　１
  type: BS
  channel: BS19_1
  serviceId: 242
  isDisabled: true
- name: Ｊ　ＳＰＯＲＴＳ　２
  type: BS
  channel: BS19_2
  serviceId: 243
  isDisabled: true
- name: Ｊ　ＳＰＯＲＴＳ　３
  type: BS
  channel: BS19_3
  serviceId: 244
  isDisabled: true
- name: ＷＯＷＯＷプラス
  type: BS
  channel: BS21_0
  serviceId: 252
  isDisabled: true
- name: 日本映画専門ｃｈ
  type: BS
  channel: BS21_1
  serviceId: 255
  isDisabled: true
- name: グリーンチャンネル
  type: BS
  channel: BS21_2
  serviceId: 234
  isDisabled: true
- name: ディズニーｃｈ
  type: BS
  channel: BS23_0
  serviceId: 256
  isDisabled: true
- name: ＴＢＳチャンネル１
  type: CS
  channel: CS2
  serviceId: 296
  isDisabled: true
- name: テレ朝チャンネル１
  type: CS
  channel: CS2
  serviceId: 298
  isDisabled: true
- name: テレ朝チャンネル２
  type: CS
  channel: CS2
  serviceId: 299
  isDisabled: true
- name: ディズニージュニア
  type: CS
  channel: CS2
  serviceId: 339
  isDisabled: true
- name: スカイＡ
  type: CS
  channel: CS4
  serviceId: 250
  isDisabled: true
- name: 時代劇専門ｃｈ
  type: CS
  channel: CS4
  serviceId: 292
  isDisabled: true
- name: エンタメ～テレ
  type: CS
  channel: CS4
  serviceId: 301
  isDisabled: true
- name: ＭＴＶ
  type: CS
  channel: CS4
  serviceId: 323
  isDisabled: true
- name: ホームドラマＣＨ
  type: CS
  channel: CS6
  serviceId: 294
  isDisabled: true
- name: ミュージック・エア
  type: CS
  channel: CS6
  serviceId: 324
  isDisabled: true
- name: 歌謡ポップス
  type: CS
  channel: CS6
  serviceId: 329
  isDisabled: true
- name: カートゥーン
  type: CS
  channel: CS6
  serviceId: 331
  isDisabled: true
- name: ディスカバリー
  type: CS
  channel: CS6
  serviceId: 340
  isDisabled: true
- name: アニマルプラネット
  type: CS
  channel: CS6
  serviceId: 341
  isDisabled: true
- name: ＣＮＮｊ
  type: CS
  channel: CS6
  serviceId: 354
  isDisabled: true
- name: 囲碁・将棋チャンネル
  type: CS
  channel: CS6
  serviceId: 363
  isDisabled: true
- name: ショップチャンネル
  type: CS
  channel: CS8
  serviceId: 55
  isDisabled: true
- name: 東映チャンネル
  type: CS
  channel: CS8
  serviceId: 218
  isDisabled: true
- name: Ｍｎｅｔ
  type: CS
  channel: CS8
  serviceId: 318
  isDisabled: true
- name: 日テレＮＥＷＳ２４
  type: CS
  channel: CS8
  serviceId: 349
  isDisabled: true
- name: 衛星劇場
  type: CS
  channel: CS10
  serviceId: 219
  isDisabled: true
- name: ＫＢＳ　Ｗｏｒｌｄ
  type: CS
  channel: CS10
  serviceId: 317
  isDisabled: true
- name: スポーツライブ＋
  type: CS
  channel: CS10
  serviceId: 800
  isDisabled: true
- name: スカチャン１
  type: CS
  channel: CS10
  serviceId: 801
  isDisabled: true
- name: ＧＡＯＲＡ
  type: CS
  channel: CS12
  serviceId: 254
  isDisabled: true
- name: エムオン！
  type: CS
  channel: CS12
  serviceId: 325
  isDisabled: true
- name: キッズステーション
  type: CS
  channel: CS12
  serviceId: 330
  isDisabled: true
- name: ナショジオ
  type: CS
  channel: CS12
  serviceId: 343
  isDisabled: true
- name: ザ・シネマ
  type: CS
  channel: CS14
  serviceId: 227
  isDisabled: true
- name: ファミリー劇場
  type: CS
  channel: CS14
  serviceId: 293
  isDisabled: true
- name: スーパー！ドラマＴＶ
  type: CS
  channel: CS14
  serviceId: 310
  isDisabled: true
- name: ヒストリーチャンネル
  type: CS
  channel: CS14
  serviceId: 342
  isDisabled: true
- name: ＳＫＹ　ＳＴＡＧＥ
  type: CS
  channel: CS16
  serviceId: 290
  isDisabled: true
- name: ＡＸＮ　海外ドラマ
  type: CS
  channel: CS16
  serviceId: 311
  isDisabled: true
- name: ＡＸＮミステリー
  type: CS
  channel: CS16
  serviceId: 316
  isDisabled: true
- name: スペシャプラス
  type: CS
  channel: CS16
  serviceId: 321
  isDisabled: true
- name: ＡＴ－Ｘ
  type: CS
  channel: CS16
  serviceId: 333
  isDisabled: true
- name: ＢＢＣワールド
  type: CS
  channel: CS16
  serviceId: 353
  isDisabled: true
- name: ムービープラス
  type: CS
  channel: CS18
  serviceId: 240
  isDisabled: true
- name: ゴルフネットワーク
  type: CS
  channel: CS18
  serviceId: 262
  isDisabled: true
- name: 銀河◆歴ドラ・サスペ
  type: CS
  channel: CS18
  serviceId: 305
  isDisabled: true
- name: 女性ｃｈ／ＬａＬａ
  type: CS
  channel: CS18
  serviceId: 314
  isDisabled: true
- name: フジテレビＯＮＥ
  type: CS
  channel: CS20
  serviceId: 307
  isDisabled: true
- name: フジテレビＴＷＯ
  type: CS
  channel: CS20
  serviceId: 308
  isDisabled: true
- name: フジテレビＮＥＸＴ
  type: CS
  channel: CS20
  serviceId: 309
  isDisabled: true
- name: スペースシャワーＴＶ
  type: CS
  channel: CS20
  serviceId: 322
  isDisabled: true
- name: ＱＶＣ
  type: CS
  channel: CS22
  serviceId: 161
  isDisabled: true
- name: ＴＢＳチャンネル２
  type: CS
  channel: CS22
  serviceId: 297
  isDisabled: true
- name: ＦＯＸ
  type: CS
  channel: CS22
  serviceId: 312
  isDisabled: true
- name: ＴＢＳ　ＮＥＷＳ
  type: CS
  channel: CS22
  serviceId: 351
  isDisabled: true
- name: 映画・ｃｈＮＥＣＯ
  type: CS
  channel: CS24
  serviceId: 223
  isDisabled: true
- name: 日テレジータス
  type: CS
  channel: CS24
  serviceId: 257
  isDisabled: true
- name: ＭＯＮＤＯ　ＴＶ
  type: CS
  channel: CS24
  serviceId: 295
  isDisabled: true
- name: 日テレプラス
  type: CS
  channel: CS24
  serviceId: 300
  isDisabled: true
- name: AT-X HD
  type: SKY
  channel: ATXHD
  serviceId: 33435
  satelite: JCSAT3A
  isDisabled: true
- name: AXN HD
  type: SKY
  channel: AXNHD
  serviceId: 33418
  satelite: JCSAT4A
  isDisabled: true
- name: BS SPTV
  type: SKY
  channel: CH585
  serviceId: 33353
  satelite: JCSAT3A
  isDisabled: true
